export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  PLAN_NOT_SUBMITTABLE: "PLAN_NOT_SUBMITTABLE",
  PLAN_NOT_APPROVABLE: "PLAN_NOT_APPROVABLE",
  PLAN_NOT_REJECTABLE: "PLAN_NOT_REJECTABLE",
  PLAN_NOT_ARCHIVABLE: "PLAN_NOT_ARCHIVABLE",
  PLAN_APPROVAL_REQUIRED: "PLAN_APPROVAL_REQUIRED",
  PLAN_RETURNED_EXECUTION_BLOCKED: "PLAN_RETURNED_EXECUTION_BLOCKED",
  STEP_ORDER_BLOCKED: "STEP_ORDER_BLOCKED",
  STEP_NOT_STARTABLE: "STEP_NOT_STARTABLE",
  STEP_NOT_FINISHABLE: "STEP_NOT_FINISHABLE",
  REJECTION_REASON_REQUIRED: "REJECTION_REASON_REQUIRED",
  PLAN_ARCHIVED_LOCKED: "PLAN_ARCHIVED_LOCKED",
  NETWORK_ERROR: "NETWORK_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
