export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  PLAN_NOT_APPROVED: "PLAN_NOT_APPROVED",
  PLAN_EDIT_LOCKED: "PLAN_EDIT_LOCKED",
  PLAN_REJECTION_REASON_REQUIRED: "PLAN_REJECTION_REASON_REQUIRED",
  PLAN_STEPS_INCOMPLETE: "PLAN_STEPS_INCOMPLETE",
  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  STEP_REGISTER_LOCKED: "STEP_REGISTER_LOCKED",
  STEP_EXECUTION_FROZEN: "STEP_EXECUTION_FROZEN",
  STEP_INVALID_TRANSITION: "STEP_INVALID_TRANSITION",
  STEP_ORDER_BLOCKED: "STEP_ORDER_BLOCKED",
  RELIC_NOT_FOUND: "RELIC_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
